import { ArrowRight, CalendarDays, Check, ChevronRight, CircleAlert, Clock3, ShieldCheck, Wrench } from 'lucide-react'
import { Link } from 'react-router-dom'
import { activities, conformity, metrics } from '../modules/dashboard/data'

export function DashboardPage() {
  return <>
    <div className="page-heading"><div><span className="eyebrow">VISÃO GERAL DA UNIDADE</span><h1>Dashboard</h1><p>Acompanhe a qualidade e mantenha sua operação em conformidade.</p></div><Link className="button secondary" to="/agenda"><CalendarDays size={17} />Ver agenda<ArrowRight size={16} /></Link></div>
    <section className="welcome-banner"><span className="welcome-icon"><ShieldCheck size={27} /></span><div><h2>Boas práticas. Melhores resultados.</h2><p>Uma visão integrada para cuidar da qualidade em cada etapa da produção.</p></div><span className="demo-label">Dados demonstrativos</span></section>
    <section className="metrics-grid" aria-label="Indicadores da unidade">{metrics.map(({ label, value, detail, icon: Icon, tone }) => <article className="metric-card panel" key={label}><div className="metric-top"><span>{label}</span><span className={`metric-icon ${tone}`}><Icon size={20} /></span></div><strong className="metric-value">{value}</strong><p>{detail}</p></article>)}</section>
    <div className="dashboard-grid">
      <section className="panel activities-panel"><div className="panel-heading"><div><h2>Atividades de hoje <span className="count">12</span></h2><p>Destaques da programação da sua equipe</p></div><Link className="text-link" to="/agenda">Ver todas<ArrowRight size={15} /></Link></div><div className="activity-table"><div className="activity-table-heading"><span>Horário / Atividade</span><span>Responsável</span><span>Status</span></div>{activities.map(activity => <Link to={activity.path} className="activity-row" key={activity.title}><div className="activity-info"><span className="activity-time">{activity.time}</span><div><strong>{activity.title}</strong><small>{activity.area}</small></div></div><span className="activity-owner"><span className="avatar small">{activity.initials}</span>{activity.owner}</span><span className={`badge ${activity.tone}`}>{activity.status === 'Concluída' && <Check size={12} />}{activity.status}</span></Link>)}</div><div className="panel-bottom"><span><span className="status-dot" />4 de 12 atividades concluídas</span><span>33% do dia</span></div></section>
      <section className="panel alerts-panel"><div className="panel-heading"><div><h2>Alertas <span className="count alert-count">3</span></h2><p>Pontos que merecem atenção</p></div><CircleAlert size={19} className="muted" /></div><div className="alerts-list"><Link to="/agenda" className="alert-item"><span className="metric-icon red"><Clock3 size={18} /></span><div><h3>3 atividades vencidas</h3><p>Revise os prazos e organize as pendências da equipe.</p><span className="text-link">Consultar atividades<ChevronRight size={14} /></span></div></Link><Link to="/equipamentos" className="alert-item"><span className="metric-icon orange"><Wrench size={18} /></span><div><h3>Calibrações se aproximando</h3><p>4 equipamentos com calibração prevista nos próximos 30 dias.</p><span className="text-link">Ver equipamentos<ChevronRight size={14} /></span></div></Link><Link to="/nao-conformidades" className="alert-item"><span className="metric-icon orange"><CircleAlert size={18} /></span><div><h3>5 não conformidades abertas</h3><p>Acompanhe a evolução dos planos de ação.</p><span className="text-link">Acompanhar ações<ChevronRight size={14} /></span></div></Link></div></section>
      <section className="panel conformity-panel"><div className="panel-heading"><div><h2>Visão geral da conformidade</h2><p>Panorama dos principais controles de BPF</p></div><Link className="text-link" to="/relatorios">Ver relatórios<ArrowRight size={15} /></Link></div><div className="conformity-content"><div className="conformity-summary"><div className="conformity-ring" role="img" aria-label="Conformidade geral de 94 por cento"><div><strong>94<span>%</span></strong><small>Conformidade geral</small></div></div><span className="badge green"><ShieldCheck size={14} />Acima da meta de 90%</span></div><div className="conformity-bars">{conformity.map(item => <div className="conformity-item" key={item.label}><div><span>{item.label}</span><strong>{item.value}%</strong></div><meter min={0} max={100} value={item.value} aria-label={`Conformidade de ${item.label}`}>{item.value}%</meter></div>)}</div><div className="conformity-note"><span className="metric-icon green"><ShieldCheck size={23} /></span><h3>Qualidade é um compromisso diário.</h3><p>Mantenha os registros atualizados e acompanhe os indicadores para fortalecer as boas práticas na sua unidade.</p><Link className="text-link" to="/auditorias">Acessar auditorias<ArrowRight size={15} /></Link></div></div></section>
    </div>
  </>
}
